// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHeroesApi.Infrastructure.Data;

#nullable disable

namespace SuperHeroesApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SuperDbContext))]
    [Migration("20260924203616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SuperHeroesApi.Domain.Entities.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("HeroName")
                        .IsUnique();

                    b.ToTable("Heros");
                });

            modelBuilder.Entity("SuperHeroesApi.Domain.Entities.HeroSuperpower", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuperpowerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroId", "SuperpowerId");

                    b.HasIndex("SuperpowerId");

                    b.ToTable("HerosSuperpowers");
                });

            modelBuilder.Entity("SuperHeroesApi.Domain.Entities.Superpower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Superpowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Força física sobre-humana",
                            Name = "Super Força"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Capacidade de voar",
                            Name = "Voo"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Capacidade de se tornar invisível",
                            Name = "Invisibilidade"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Capacidade de ler mentes",
                            Name = "Telepatia"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Capacidade de se teletransportar",
                            Name = "Teletransporte"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Velocidade sobre-humana",
                            Name = "Super Velocidade"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Capacidade de se curar rapidamente",
                            Name = "Regeneração"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Capacidade de controlar mentes",
                            Name = "Controle Mental"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Capacidade de disparar raios laser dos olhos",
                            Name = "Raios Laser"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Capacidade de esticar o corpo",
                            Name = "Elasticidade"
                        });
                });

            modelBuilder.Entity("SuperHeroesApi.Domain.Entities.HeroSuperpower", b =>
                {
                    b.HasOne("SuperHeroesApi.Domain.Entities.Hero", "Hero")
                        .WithMany("HerosSuperpowers")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperHeroesApi.Domain.Entities.Superpower", "Superpower")
                        .WithMany("HerosSuperpowers")
                        .HasForeignKey("SuperpowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Superpower");
                });

            modelBuilder.Entity("SuperHeroesApi.Domain.Entities.Hero", b =>
                {
                    b.Navigation("HerosSuperpowers");
                });

            modelBuilder.Entity("SuperHeroesApi.Domain.Entities.Superpower", b =>
                {
                    b.Navigation("HerosSuperpowers");
                });
#pragma warning restore 612, 618
        }
    }
}
